
server:
  port: 7002

logging:
  level:
    root: info
    handsonms: debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5

spring:
  application:
    name: recommendation-service
---

spring:
  profiles: docker

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka