version: '2.1'

services:

  gateway:
    build: ../edge-server
    mem_limit: 350m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  eureka:
    build: ../eureka
    mem_limit: 350m
#    ports:
#      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  product-service:
    build: ./product-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  recommendation-service:
    build: ./recommendation-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  review-service:
    build: review-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  product-composite-service:
    build: product-composite
    mem_limit: 350m
#    ports:
#      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker